### ISSUE TITLE
UnsupportedMediaTypeError handling

### ISSUE THREAD

**Issue by nmors** [mulesoft-labs/osprey-method-handler#15] opened 2016-03-24 04:33 UTC
UnsupportedMediaTypeError: No body sent with request for PUT /api/something with content-type "undefined"

Seems that there is no way to handle such error ?

err object appears to be empty for this case.

Please advise

Thanks

**Comment by blakeembrey** [comment] 2016-03-24 04:42
What's the expected behaviour? Can you provide a small replication to demonstrate the issue?

**Comment by blakeembrey** [comment] 2016-03-24 04:43
The RAML document, I assume, defines that you need a body and the application has not sent a body with the HTTP request.

**Comment by nmors** [comment] 2016-03-24 04:59
it's okay, i guess i can use something like:

if(err.name == "UnsupportedMediaTypeError" )){
   res.status(415);
....
}

I was just expecting err.code to have 415 in it
err.type is undefined also

**Comment by nmors** [comment] 2016-03-24 04:59
Probably this isn't a real a bug, sorry

**Comment by blakeembrey** [comment] 2016-03-24 05:22
@nmors Now I understand, cheers! It is created with `415`, it has a `status` property which means default Express.js error handlers will use the correct HTTP status code: https://github.com/mulesoft-labs/osprey-method-handler/blob/master/osprey-method-handler.js#L306.

**Comment by blakeembrey** [comment] 2016-03-24 05:25
Let me know if the `status` property helps you, it's the "standard" way in Express.js to communicate the HTTP status code (E.g. https://github.com/jshttp/http-errors/blob/master/index.js#L97).

**Comment by nmors** [comment] 2016-03-24 05:33
yep! checking error.status now for handling my errors. thanks for your help

**Comment by blakeembrey** [comment] 2016-03-24 20:01
No problem, closing it resolved :+1: It sounds like you may have been trying to do something else, just keep in mind other middleware can respond with a status error of `415` too (since it's just a HTTP code).

**Closed** 2016-03-24 20:01 UTC

**Comment by jansanchez** [comment] 2016-04-19 17:38
Hi @nmors I've the same problem. How did you solve? pls
